apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
 name: ocs-storagecluster
 namespace: openshift-storage
spec:
 # The empty label selector removes the default so components can run an all
 # worker nodes.
 labelSelector:
   matchExpressions: []
 hostNetwork: true
 externalStorage: {}
 storageDeviceSets:
 - config: {}
   count: 1
   dataPVCTemplate:
     metadata:
       creationTimestamp: null
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 1Ti
       storageClassName: gp2
       volumeMode: Block
     status: {}
   name: ocs-deviceset
   placement: {}
   portable: true
   replica: 3
   resources: {}
